# Generated by Django 3.1.7 on 2021-03-22 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CabDriver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('car_number', models.CharField(max_length=200, unique=True)),
                ('phone_number', models.CharField(max_length=13, unique=True)),
                ('license_number', models.CharField(max_length=200, unique=True)),
                ('email', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'db_table': 'cab_availability_cab_driver',
            },
        ),
        migrations.CreateModel(
            name='CabPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.CharField(max_length=200)),
                ('longitude', models.CharField(max_length=200)),
                ('cab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cab_availability.cabdriver')),
            ],
            options={
                'db_table': 'cab_availability_cab_position',
            },
        ),
    ]
